server:
  port: 0

spring:
  application:
    name: activiti-server
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/activiti_test?useUnicode=true&useSSL=false&autoReconnect=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource

  activiti:
    db-history-used: true
    history-level: full
    database-schema-update: true

mybatis-plus:
  mapperLocations: classpath*:/mapper/**/*.xml