server:
  port: 0

spring:
  application:
    name: activiti-server
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@121.199.69.99:1521:orcl
    username: crh_user
    password: cairenhui
    type: com.zaxxer.hikari.HikariDataSource
  messages:
    basename: i18n/messages
    encoding: UTF-8

mybatis-plus:
  mapperLocations: classpath*:/mapper/**/*.xm